name: Rust

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run meta crate tests
      run: cargo test --verbose
    - name: Run uint_n tests
      run: cargo test --verbose -p uint_uint_n
    - name: Run natmod_p tests
      run: cargo test --verbose -p uint_natmod_p
